# Generated by Django 2.1.3 on 2018-12-04 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('fotoProducto', models.ImageField(upload_to='fotos/')),
                ('codigoLista', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLista', models.CharField(max_length=20, verbose_name='Nombre Lista')),
                ('estadoLista', models.CharField(default='Proceso', max_length=30, verbose_name='Estado Lista')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Mascota')),
                ('costoPresupuesto', models.PositiveIntegerField(default='0', max_length=50, verbose_name='Costo Presupuestado')),
                ('costoReal', models.PositiveIntegerField(default='0', max_length=50, verbose_name='Costo Real')),
                ('descripcionLista', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ListaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lista')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigoTienda', models.AutoField(primary_key=True, serialize=False)),
                ('fotoTienda', models.ImageField(upload_to='fotos/')),
                ('nombreTienda', models.CharField(max_length=20, verbose_name='Nombre Tienda')),
                ('nombreSucursal', models.CharField(default='', max_length=20, verbose_name='Nombre Sucursal')),
                ('direccion', models.CharField(default='', max_length=50, verbose_name='Direccion')),
                ('ciudad', models.CharField(default='', max_length=30, verbose_name='Ciudad')),
                ('tipoTienda', models.CharField(default='Fisica', max_length=30, verbose_name='Tipo Tienda')),
                ('paginaWeb', models.CharField(default='', max_length=50, verbose_name='Pagina Web')),
                ('estadoTienda', models.CharField(default='Pendiente', max_length=30, verbose_name='Estado Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listausuario',
            name='codigoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
