# Generated by Django 2.1.3 on 2018-12-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='costoPresupuesto',
            field=models.PositiveIntegerField(default='0', verbose_name='Costo Presupuestado'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='costoReal',
            field=models.PositiveIntegerField(default='0', verbose_name='Costo Real'),
        ),
    ]
