# Generated by Django 2.1.3 on 2018-12-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181204_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('fotoProducto', models.ImageField(upload_to='fotos/')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('costoPresupuesto', models.PositiveIntegerField(default='0', verbose_name='Costo Presupuestado')),
                ('costoReal', models.PositiveIntegerField(default='0', verbose_name='Costo Real')),
                ('nombreTienda', models.CharField(max_length=20, verbose_name='Nombre Tienda')),
                ('descripcionProducto', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TiendaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto')),
                ('codigoTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tienda')),
            ],
        ),
        migrations.RemoveField(
            model_name='lista',
            name='costoPresupuesto',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='costoReal',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='descripcionLista',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='fotoProducto',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='nombreProducto',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default=1, max_length=20, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=1, max_length=20, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=1, max_length=20, verbose_name='Nombre Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='codigoLista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lista'),
        ),
        migrations.AddField(
            model_name='listaproducto',
            name='codigoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto'),
        ),
    ]
