# Generated by Django 2.1.3 on 2018-12-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181204_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombreTienda',
        ),
    ]
