# Generated by Django 2.1.3 on 2018-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181205_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=100)),
                ('precioreal', models.CharField(max_length=100)),
                ('tienda', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='estadoLista',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
