# Generated by Django 2.1.3 on 2018-12-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181206_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fotoProducto',
        ),
    ]
