# Generated by Django 2.1.3 on 2018-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_producto_fotoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre Producto'),
        ),
    ]
