# Generated by Django 2.1.3 on 2018-12-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181206_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='fotoTienda',
        ),
    ]
