# Generated by Django 2.1.3 on 2018-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181206_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Producto'),
        ),
    ]
