# Generated by Django 2.1.3 on 2018-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181206_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='Nombreproducto',
        ),
        migrations.AddField(
            model_name='tienda',
            name='fotoTienda',
            field=models.ImageField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
